apiVersion: v1
kind: Secret
metadata:
  name: workload-secrets-data
  namespace: tap-install
type: Opaque
stringData:
  content.yaml: |
    git:
      host: https://github.com/
      username: sharmadinesha
      token: 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
      docker: eyJhdXRocyI6eyJoYXJib3Itdm0udXMtY2VudHJhbC0wMDcubWNsb3VkLmVsYWJzLnN2Y3MuZW50c3Zjcy5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiVk13YXJlMSJ9fX0=
